[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "spotify-homepage-backend"
version = "0.1.0"

[profile.release]
debug = true

[[bin]]
name = "spotify-homepage-backend"
path = "src/main.rs"

[dependencies]
base64 = "0.11"

chrono = { version = "0.4", features = ["serde"] }

crossbeam = "0.7.3"

diesel = { version = "1.4", features = ["chrono", "mysql"] }

dotenv = "0.15.0"

hashbrown = { version = "0.7", features = ["serde"] }

lazy_static = "1.4.0"

log = "0.4"

r2d2_redis = "0.13"

rayon = "1.3"

redis = "0.15"

reqwest = { version = "0.10", features = ["blocking", "json"] }

rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev="2d8bdd457e650c58dbe45eb969d6280758927209" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket.git", rev="2d8bdd457e650c58dbe45eb969d6280758927209", features = ["json", "diesel_mysql_pool", "compression"] }

serde_json = "1.0.53"
serde = "1.0.110"
serde_derive = "1.0.110"
