[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "spotify-homepage-backend"
version = "0.1.0"

[[bin]]
name = "spotify-homepage-backend"
path = "src/main.rs"

[dependencies]
base64 = "0.10.1"

chrono = { version = "0.4.6", features = ["serde"] }

crossbeam = "0.7.1"

diesel = { version = "1.4.2", features = ["chrono"] }

dotenv = "0.14.0"

lazy_static = "1.3.0"

log = "0.4"

r2d2_redis = "0.9.0"

rayon = "1.0.3"

redis = "0.10.0"

reqwest = "0.9.15"

rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev="e458df094ffa6e4a793a9b8257950a0409f71487" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket.git", rev="e458df094ffa6e4a793a9b8257950a0409f71487", features = ["json", "diesel_mysql_pool", "compression"] }

serde_json = "1.0.39"
serde = "1.0.90"
serde_derive = "1.0.90"
