[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "spotify-homepage-backend"
version = "0.1.0"
[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }

diesel = { version = "1.4.2", features = ["chrono"] }

reqwest = "0.9.15"

rocket = "0.4.0"
rocket_contrib = { version = "0.4.0", features = ["json", "diesel_mysql_pool"] }

serde_json = "1.0.39"
serde = "1.0.90"
serde_derive = "1.0.90"
